version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Running install phase..."
      - npm ci
      - npm install -g aws-cdk
  pre_build:
    commands:
      - echo "Running pre-build (lint/tests, etc.)..."
      # - npm run lint
      - npm run test
  build:
    commands:
      - echo "Synthesizing the CDK stack..."
      - npm run build
      - npm run cdk:synth
      - ls -la cdk.out/
  post_build:
    commands:
      - echo "Build phase complete."
      - aws cloudformation package --template-file cdk.out/ProductManagementStack.template.json --s3-bucket productmanagementstack-artifactbucket7410c9ef-kfx7zcavhapm --output-template-file packaged-template.json
artifacts:
  files:
    - cdk.out/*.template.json
    - cdk.out/*.assets.json
    - cdk.out/*.zip
  discard-paths: yes