version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Running install phase..."
      - npm ci
      - npm install -g aws-cdk
  pre_build:
    commands:
      - echo "Running pre-build (lint/tests, etc.)..."
      # - npm run lint
      - npm run test
  build:
    commands:
      - echo "Synthesizing the CDK stack..."
      - npm run cdk:synth
      - ls -la cdk.out/
  post_build:
    commands:
      - echo "Build phase complete."
artifacts:
  files:
    - 'cdk.out/**/*'
  discard-paths: no
