version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install
  # TODO: later
  # pre_build:
  #   commands:
  #     - echo Running pre-build steps...
  #     - npm run lint
  build:
    commands:
      - echo Building the project...
      - npm run build
      - echo Running tests...
      - npm test
  post_build:
    commands:
      - echo Packaging and deploying Lambda functions...
      - npm run deploy

artifacts:
  files:
    - dist/**
    - src/**
    - cdk.out/**
  discard-paths: no
